### ISSUE TITLE
Could not find module ‘Distribution.Extra.Doctest’ -- 

### ISSUE THREAD

**Issue by testexplode** [phadej/cabal-doctest#24] opened 2017-10-02 20:46 UTC
If I want to compile for example comonad or parsers I get the following errors:

```
comonad-5.0.2-9P9ZbrB2lYo8asSaS7XXK9 failed during the configure step. The
exception was:
dieVerbatim: user error (cabal: '/usr/bin/ghc' exited with an error:

/tmp/cabal-tmp-6837/comonad-5.0.2/dist/setup/setup.hs:12:1: error:
Could not find module ‘Distribution.Extra.Doctest’
There are files missing in the ‘cabal-doctest-1.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
|
12 | import Distribution.Extra.Doctest ( defaultMainWithDoctests )
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
```

I'm using manjaro-linux,

My versions are:
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library 
The Glorious Glasgow Haskell Compilation System, version 8.2.1

Due to this error many packages that Idris is using are not buildable. 

I tried to use the patch from issue #19, but it did not work, still the same error.

**Comment by RyanGlScott** [comment] 2017-10-03 11:53
It sounds like something is screwed up wkth your installation of `cabal-doctest`. Does `ghc-pkg check` say anything about it?

**Comment by testexplode** [comment] 2017-10-03 13:45
Noc it says nothing about it.

It says:
```
[me@computer ~]$ ghc-pkg check
Warning: haddock-interfaces: /home/me/.cabal/share/doc/x86_64-linux-ghc-8.2.1/fail-4.9.0.0/html/fail.haddock doesn't exist or isn't a file
Warning: haddock-interfaces: /usr/share/doc/haskell-zlib/html/zlib.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-zlib/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-text/html/text.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-text/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-tar/html/tar.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-tar/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-stm/html/stm.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-stm/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-random/html/random.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-random/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-parsec/html/parsec.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-parsec/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-network/html/network.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-network/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-network-uri/html/network-uri.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-network-uri/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-mtl/html/mtl.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-mtl/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-http/html/HTTP.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-http/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-hashable/html/hashable.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-hashable/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-hackage-security/html/hackage-security.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-hackage-security/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-edit-distance/html/edit-distance.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-edit-distance/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-ed25519/html/ed25519.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-ed25519/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-echo/html/echo.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-echo/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-cryptohash-sha256/html/cryptohash-sha256.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-cryptohash-sha256/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-base64-bytestring/html/base64-bytestring.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-base64-bytestring/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-base16-bytestring/html/base16-bytestring.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-base16-bytestring/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-async/html/async.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-async/html doesn't exist or isn't a directory
```

**Comment by RyanGlScott** [comment] 2017-10-03 13:47
OK. I'm grasping at straws a bit here, because I'm unable to reproduce the issue. Can you try uninstalling and reinstalling `cabal-doctest` to see if that makes a difference?

**Comment by testexplode** [comment] 2017-10-03 14:50
I tried to reinstall doctest, no change.
I made the installation of idris ```cabal install idris``` again on a virtual machine that has just been updated to ghc 8.2.1 (so no old packages): no change, same error

Perhaps it has something to do with the new dynamic linking in arch and manjaro ?

I had to change the ~/.cabal/config with
```
library-vanilla: False
shared: True
executable-dynamic: True
```

**Comment by RyanGlScott** [comment] 2017-10-03 18:32
Ah! Thank you, that `~/.cabal/config` info was very helpful. I'm now able to reproduce the issue locally on my Ubuntu machine if I run:

```
$ cabal install --disable-library-vanilla distributive-0.5.3
```

I'm not sure yet _why_ exactly this is failing, though.

**Comment by RyanGlScott** [comment] 2017-10-03 22:50
My gut feeling is that `cabal` is to blame here, given that this seems to happen specifically with `custom-setup` scripts. I've opened https://github.com/haskell/cabal/issues/4812 to track this.

**Comment by RyanGlScott** [comment] 2018-01-26 02:54
Alas, there's nothing more we can do on `cabal-doctest`'s end, so I'll close this in favor of haskell/cabal#1720.

**Closed by RyanGlScott** 2018-01-26 02:54 UTC
